go-debos/debos

debos.go, download_action.go, overlay_action.go, raw_action.go, unpack_action.go
Added new action 'download' with unpack and install abilities.
=> Download action

actions/ostree_deploy_action.go
Signed-off-by: Sjoerd Simons <sjoerd.simons@collabora.co.uk>
=> actions: set normalized key for AppendKernelCmdline

actions/debootstrap_action.go
Add description of 'merged-usr' property.
=> actions: debootstrap: description of 'merged-usr'

cmd/debos/debos.go
os.Exit() call do not run deferred functions.
This leads to incorrect cleanup of resources and files in certain cases.
=> Allow to finish all deferred functions on os.Exit()

README.md
Add useful links to documentation and examples to use the tool.
Signed-off-by: Héctor Orón Martínez <zumbi@debian.org>
=> README.md: add links to actions and examples

actions/image_partition_action.go
This is a property allowing to use 'hacked' GPT with special parted
version: https://repositories.apertis.org/debian/pool/tools/p/parted/
It allows to write boot binary to sector 2 without damaging GPT.
=> actions: image-partition: add 'gpt_gap' property

actions/image_partition_action.go, actions/ostree_deploy_action.go, cmd/debos/debos.go
Allow to use ostree_deploy action without the target image.
=> Ostree deploy

actions/run_action.go
Scripts passed to "Run" action are strings containing full path to script
with arguments. Debos fails to run it tr to start the whole string as a script.
Add possibility to start scripts with additional arguments.
Correct mount points for scripts with arguments in chrooted environment.
=> actions: run: allow to start scripts with arguments

LICENSE
Signed-off-by: Héctor Orón Martínez <hector.oron@collabora.co.uk>
=> LICENSE: add copyright holder

cmd/debos/debos.go
/scrach -> /scratch
createing -> creating
(Also move 'outer' to next line to avoid going over 80 char limit)
=> Fix a couple of code comment typos

actions/run_action.go
This allows recipes to run command line using files from the
recipe directory.
Signed-off-by: Frédéric Dalleau <frederic.dalleau@collabora.com>
=> Add RECIPEDIR environment variable

TODO
now is the TODO list aware of it
=> v1.0 is out, already renamed

actions/ostree_commit_action.go, filesystem.go
A few fixes I made while getting started with debos. Just details..
=> Fix details

commands.go
Signed-off-by: Sjoerd Simons <sjoerd.simons@collabora.co.uk>
=> Recognize the riscv64 architecture

actions/image_partition_action.go
Every so often we've seen races where seemingly the partition device
disappeared when trying to use it. These became a bit more frequent
after some speedups in fakemachine. Digging deeper it turns out that
udev helpfully ask the kernel to rescan the partition table when it gets
told via inotify that something might have written to it.
As we're using parted, which already tells the kernel about partitions
it created, this gets rather confusion. The new partition device would pop up
(triggered by parted), parted would close the disk device node; This
then would notify udev, which asked the kernel to rescan the partition
table on the device *again*, which in turn causes all the partition
device nodes to disappear and re-appear, leaving a nice window for
things to go horribly horribly wrong. …
=> Fix partition races while partitioning

README.md
Found the needed help via https://github.com/go-debos/debos/issues/61.
Tested this on Debian Testing and Stable  (stretch)
=> Document installation under Debian

actions/ostree_commit_action.go
Allow to add metadata key-value pairs into ostree commit.
Parameter `collection-id` allows bindings to collection refs (collection id + branch). This add metadata information into commit: `ostree.collection-binding` and `ostree.ref-binding` (binding only to created branch).
Requires libostree minimal version 2018.6.
Depends on changes proposed in https://github.com/sjoerdsimons/ostree-go/pull/1
=> ostree-commit: add support of metadata and collections

docker/Dockerfile
Useful compression utilities which may be used by debos
Fixes #155
=> docker: Add compression utilities support

docker/Dockerfile
Ordered packages list simplify maintenance.
=> docker: Re-order packages alphabetically

actions/image_partition_action.go
We might want to enable specific features during a filesystem creation,
as it can be difficult and/or cause issues to enable them afterwards.
This commit introduces a new 'features' field to partition definitions,
and makes sure the corresponding features are enabled when creating the
filesystem.
=> image-partition: Enable filesystem features on fs creation

commands.go
If the resolv.conf in chrooted environment changed to symlink and point to
non-existing file, the os.Stat() fail the check of file existence.
Use os.Lstat() call instead and add additional checks during the resolv.conf
restore phase.
Fixes: #190
=> commands: check if the chrooted resolv.conf is a symlink

actions/image_partition_action.go
Currently the `mountpoints` are mounted in the fakemachine in the order defined
by the recipe. This is confusing for users so sort the mountpoints in a sane
order before they are mounted.
This patch sorts the mountpoints so that (if defined) the root partition would
always be mounted first, then in ascending order of how many slashes ('/')
are in the mountpoint so that the parents are mounted first.
The current verbatim syntax for mountpoints where the recursive parent filesystems
are mounted before the children could be as follows:
```
- action: image-partition
imagename: mountpoints-order.img
imagesize: 5MB
partitiontype: gpt
partitions:
- name: root
fs: ext4
start: 0M
end: 1M
- name: opt
fs: ext4
start: 2M
end: 3M
- name: opt_test
fs: ext4
start: 4M
end: 5M
mountpoints:
- mountpoint: / …
```
=> actions/image_partition: sort mountpoints by position in filesystem hierarchy before mounting

actions/image_partition_action.go
The image is locked while partitioning and mounting, which has a side effect of
not running udev rules so there are no entries for the freshly partitioned disk
under the children of `/dev/disk`.
Currently the workaround is to call partprobe in the recipe, which creates the
entries but we should do this as part of the image-partition action so that no
magic is needed in the recipe.
Fixes: f91e2b2c2789 ("Fix partition races while partitioning")
Resolves: #154
=> actions/image_partition: trigger udev rules after image-partition completion

actions/image_partition_action.go
A common user complaint is the result of mounting a filesystem on top of another
can be confusing. So do not allow duplicate mountpoints.
Also better not allow multiple partitions with the same name.
Resolves: #176
Resolves: #178
=> actions/image_partition: do not allow duplicate partitions or mountpoints

actions/debootstrap_action.go
Added stages "Verify" and "PreMachine" allowing to use secret files
outside of recipe directory tree (both absolute and relative paths
are supported).
Verification stage ensures that configuration files from options
are existing on file system.
This is needed for cases if secret files are not the part of Debos
recipe directory and useful for CI.
This MR completely overrides https://github.com/go-debos/debos/pull/230
=> action/debootstrap: allow to use files outside of RecipeDir

README.md, doc/man/create_manpage.sh
Spelling and indentation fixes
=> Tiny manpage fixes

docker/Dockerfile
Add the git package to the docker image.
=> docker: Add git package

actions/image_partition_action.go
These patches provide setting for volume id of vfat, partition table uuid (disk identifier) 
and partition uuid (only for gpt) instead of random values.
The purpose  is controlling random data and achieve reproducible builds.
=> Allow setting volume id, partition table uuid, partition uuid

go.mod, go.sum
=> Update go.mod for new fakemachine tag

docker/Dockerfile
=> docker: Install qemu-img disk imaging utility

.github/workflows/ci.yaml
=> Use correct variable for Dockerhub image

actions/image_partition_action.go
Newer systemd/udev versions will delay processing events for block devices if another process holds an exclusive file lock, which is meant to improve coordination with e.g. partitioners.
This also means `udevadm settle` will block until it hits a timeout if being called while a lock is held. Which happens with the current debos locking scheme (holding the lock for all paritioning operations) due to Debians parted running `udevadm settle` after committing partition changes.
However the debos current locking will equivalently be problematic when partitioning tools will take over systemds device locking recommendations as they'll want to flock the device themselves.
To fix both current and future issues change the debos locking scheme to *only* hold an exclusive lock for operations using the …
=> image-partition: Minimize the image lock scope

README.md
=> Include non-free-firmware component in Simple example

actions/pack_action.go, archiver.go
pigz does gzip compression on multiple cores and multiple processors
and there is improvement in compression time on multi core machines.
Use pigz for gzip compression if installed on the host machine.
Fixes: #218
Signed-off-by: Vignesh Raman <vignesh.raman@collabora.com>
=> actions: pack/unpack: use pigz for compression

.github/workflows/ci.yaml
With the github upgraded to newer/bigger runners virtualisation seems to work so run those tests on the github runners again
=> Use github runners for kvm tests

go.mod, go.sum
=> Bump to Go 1.23

.github/workflows/ci.yaml, cmd/debos/debos.go, docker/Dockerfile
Based on the feedback received for fakemachine: https://github.com/go-debos/fakemachine/pull/220
**Draft because the other PR is not yet approved**
=> cmd: define Version at build time from git to avoid hardcoded version

LICENSE
Fix: #572
Next step is to add REUSE  tags and a CI job like in https://github.com/go-debos/test-containers/pull/36
=> LICENSE: Update copyright years
