go-debos/debos

actions/image_partition_action.go

FAT partitions can't be mounted with 'fat32' partition type.
'vfat' partition type must be used for 'fat32' entries for correct mount.

actions: image-partition: fix fstab entry generation for 'fat32'

---

actions/debootstrap_action.go
actions/filesystem_deploy_action.go
actions/ostree_deploy_action.go

Some of properties can't be recognized by YAML parser due missed quotes.

actions: yaml typo fix

---

filesystem.go

Fix typo leading to incorrect error message in case of any problems
with links during FS copying.

Fix typo in CopyTree function

---

cmd/debos/debos.go
recipe/recipe.go
recipe/recipe_test.go

Recipe configuration file parsing has been moved from main package of 'debos'
tool to package 'recipe'. This change combines all things related to
'debos' configuration file in the single package allowing to re-use parsing
in other tools and simplify tests creation.
Package 'recipe' is now responsible for templating mechanism and YAML parsing.

recipe: parse configuration in 'recipe' package

---

actions/debootstrap_action.go
recipe/recipe.go

Add new property 'merged-usr' for 'debootstrap' action.
By default it is set to 'true' for usage filesystem with
merged '/usr'. If set to 'false' then classic FHS will be used.
Fixes #17.

actions: debootstrap: add 'merged-usr' property

---

.gitignore
actions/actions_doc.go
actions/apt_action.go
actions/debootstrap_action.go
actions/download_action.go
actions/filesystem_deploy_action.go
actions/image_partition_action.go
actions/ostree_commit_action.go
actions/ostree_deploy_action.go
actions/overlay_action.go
actions/pack_action.go
actions/raw_action.go
actions/run_action.go
actions/unpack_action.go
recipe/recipe.go

Add description of each available action and properties allowed by actions.
Used 'godoc' format to keep actions documentation in one place with implementation.

 actions: add description of actions 

---

actions/download_action.go
actions/unpack_action.go
archiver.go
archiver_test.go

Common approach for working with archives is introduced.
Any supported archive type must to satisfy 'Archiver' interface.
Example of file unpacking:
```
archive, _ := debos.NewArchive("file.ext")
archive.Unpack("destination")
```
Three archive types are supported:
- tar (with and without compression)
- zip
- debian packages
Fixes #8

Rework of archiver for supporting different archive types

---

commands.go
os.go

Disabled services start/stop for commands running in chroot.
This also prevents services from start during packages install.

commands: disable services for commands running in chroot

---

action.go
cmd/debos/debos.go
debug.go

Launch interactive shell in context of failed action for issues investigation and debug.
Add options to debos:
--debug-shell -- to start a shell in case of any failure
--shell <path> -- use selected shell instead of default bash
Fixes #30 

debug: run interactive shell on error

---

cmd/debos/debos.go

Warn user and return an error exit code in case if recipe file is not exists.

debos: add error message if recipe file is absent

---

actions/image_partition_action.go

Future API for fakemachine will return the device path of a created
image inside a fakemachine; Update debos to support that, which also
nicely removes the /dev/vda hardcoding
Signed-off-by: Sjoerd Simons <sjoerd.simons@collabora.co.uk>

Adjust for fakemachine image API update

---

actions/image_partition_action.go

Naming scheme by disk ID provided by udevd uses '-part' suffix for partitions.
Allow to use correct partition names in case if disk path is
'/dev/disk/by-id/'.

actions: image-partition: allow to use disks by ID

---

actions/image_partition_action.go

'vfat' filesystem type is widespread name for FAT FS in *nix-world.
Add alias 'vfat' to 'fat32' filesystem type.
Add support of partitions creation without filesystem.

actions: image-partition: add alias 'vfat' for 'fat32'

---

actions/filesystem_deploy_action.go

Use correct path for origin 'filesystem'. It must be changed
as soon as we point 'Rootdir' to mounted image.

actions: filesystem_deploy: fix path for 'filesystem' origin

---

actions/image_partition_action.go

Add error check for 'udevadm' to be sure it is works as expected.

actions: image-partition: add error check on 'udevadm' call

---

actions/image_partition_action.go

Do not try to start 'blkid' on partitions without filesystem.
Modern versions of 'blkid' return empty string and error code 0.
Old versions of 'blkid'  (Debian Jessie) fails with error code 2
and this breaks the build.

actions: image-partition: do not need UUID on partitions without FS

---

actions/run_action.go

Need to pass URI as a script argument, but CleanPathAt() convert
multiple slash symbols to the single one.

action: run: fix passing of multiple '/' symbols for script arguments

---

actions/ostree_deploy_action.go

Use correct path for `filesystem` origin if rootfs has been
changed to image mountpoint.

action: ostree-deploy: fix 'filesystem' origin

---

actions/pack_action.go
actions/run_action.go
cmd/debos/debos.go

This branch makes some minor documentation fixes that I would have found useful when learning to use debos. See also #84 (which doesn't duplicate this).
* run: Document the environment variables that will be set if !chroot
* pack: Document archive as relative to artifacts directory
* cmd: Document artifacts directory
* cmd: Give a hint about template variable syntax

Improve help and documentation

---

actions/debootstrap_action.go

In failure cases, debootstrap's stdout/stderr doesn't usually tell
the whole story.
Signed-off-by: Simon McVittie <smcv@collabora.com>
Fixes: #83

debootstrap: Output the debootstrap log if it fails

---

cmd/debos/debos.go

<https://github.com/go-debos/fakemachine/pull/29> hides boot/console
messages by default. Add a `--show-boot` option to bring them back,
in case we need to debug a failing boot.

cmd: Reinstate the ability to show fakemachine boot/console messages

---

commands.go

Signed-off-by: Ana Guerrero Lopez <ana.guerrero@collabora.com>

Recognize all the mips architectures in Debian: mips, mipsel, mips6el

---

README.md

Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
`debootstrap` is quite obvious, but I think worth mentioning
`qemu` packages are required by `fakemachine`

README.md: add install dependencies

---

actions/debootstrap_action.go

Merged /usr is the default since debootstrap 1.0.102.
This change makes debos require debootstrap 1.0.83 or later.
Fixes: #115

debootstrap: Explicitly disable merged /usr if not requested

---

actions/run_action.go

This is useful if the command you're running is very long, and in particular if it has non-trivial command-line arguments.

Add the ability to set a custom label for a Run command

---

actions/image_partition_action.go

HFS and HFS+ filesystems are not handled the same by parted and the
kernel: for instance, HFS+ is named 'hfsplus' in the kernel, but
parted expects 'hfs+' or 'hfsx' (case-sensitive variant).
This patch fixes debos behavior in that case and implements the
proper command-line options when formatting these filesystems.
debos will now recognize and properly handle the 'hfs', 'hfsplus'
and 'hfsx' filesystem types.
Signed-off-by: Arnaud Ferraris <arnaud.ferraris@collabora.com>

Add support for HFS/HFS+ filesystems in image-partition action

---

actions/debootstrap_action.go

debos creates a sources.list file based on Mirror and Components from
the specification. However the only mandatory property for the
debootstrap action is suite.
Currently not specifying Mirror and/or Components results in a faulty
sources.list. This patch adds default values for the Mirror and
Components properties fixing the issue. It also document the defaults.
Signed-off-by: Peter Senna Tschudin <peter.senna@collabora.com>

debootstrap_action: add defaults for Mirror and Components

---

actions/filesystem_deploy_action.go

Additional option 'append-kernel-cmdline' as we have for
'ostree-deploy' allows to fill `/etc/kernel/cmdline` config
with custom boot parameters.

filesystem_deploy_action: add option for kernel parameters

---

actions/debootstrap_action.go

When multiple components are set for debootstrap action (like in README
simple example), image creation fails with following error:
2019/01/22 17:12:56 debootstrap.log | /debootstrap/debootstrap: 1363: /debootstrap/debootstrap: cannot open //var/lib/apt/lists/debootstrap.invalid_dists_sid_main|non-free_binary-arm64_Packages: No such file
2019/01/22 17:12:56 Action `debootstrap` failed at stage Run, error: exit status 2
The main and non-free component names are merged in
debootstrap.invalid_dists_sid_main|non-free_binary-arm64_Packages filename.
2nd stage of debootstrap does not need --components option.

Fix debootstrap failed with multiple components

---

actions/apt_action.go

When using unsigned repositories apt action is unable to install
packages, this option allows a setting to install from unauthenticated
repositories.
Signed-off-by: Héctor Orón Martínez <hector.oron@collabora.com>

apt: allow unathenticated packages installation

---

actions/ostree_deploy_action.go

Map Collection ID to internal structure of remote adding this
information into repo config file for selcted remote.

ostree-deploy: add collection_id option

---

cmd/debos/debos.go

Slice of structs dump are not correctly aligned in case of recursive calls.
Use correct numbers of spaces, like for other type dumps.

cmd: Fix slice of structs dump

---

actions/image_partition_action.go

Enable filesystems check by default by setting `fs_passno` in fstab.
Allow to disable filesystem check on partition by setting flag `fsck`
to `false`.

image-partition: add `fsck` flag

---

doc/examples/example.yaml

We declared the suite variable (defaulting to stretch), but only used it
for the filename and not for building the OS, which took a hardcoded
suite name.
Use the suite variable in OS building, changing the default to buster to
match the previous hard-coding.
Signed-off-by: Daniel Stone <daniels@collabora.com>

doc/examples: Actually use suite variable

---

README.md
docker/README.md

The usage of the container as an executable does not seems to be
straightforward.
Add a warning in docker/README.md and add container installation reference
in main README.md.

docker: Container should be used as an executable

---

actions/overlay_action.go

Remove a stray 'i' character from overlay action documentation.

Fix extremly tiny typo in the docs for the overlay action

---

commands.go

It looks like the comments for CHROOT_METHOD_NSPAWN and
CHROOT_METHOD_NONE have been swapped
Signed-off-by: Daniel Sangorrin <daniel.sangorrin@toshiba.co.jp>

commands: fix chroot method comments

---

actions/run_action.go

`/script` directory is left in target rootfs. Moving the target bind
mount to `/tmp` allows to avoid additional step for removing this directory
for all projects calling own scripts in chrooted environment.
Fixes #151

Move target bind mount for scripts to tmp

---

actions/image_partition_action.go

As described in mkfs.vfat(8) the default is to create either fat12,
fat16 or fat32 based on partition size.
This can come as an unlucky surprise whem used with something that has a
buggy fat implementation which only works with fat32, eg. some
revisions of the raspberry pi boot rom.
For more info see bottom of ("Troubleshooting"):
https://www.raspberrypi.org/documentation/hardware/computemodule/cm-emmc-flashing.md
This commit changes so we explicitly say use fat32 always, as fat12 and
fat16 are likely rare enought that noone really wants to use them when
creating a new image. This might be worthy of a release notes news entry
in case someone wonders why their image suddenly changed using the same
unmodified recipe with different versions of debos.
Fixes: #169

Always create fat32 filesystem on vfat partitions

---

actions/ostree_deploy_action.go

Sometimes `umount` fails after `ostree-deploy` with following error:
```
2019/08/26 14:08:51 ==== Deploying ostree onto image ====
2019/08/26 14:08:57 ==== List files on ostreetestarmhf ====
2019/08/26 14:08:59 Warning: Failed to get unmount /: device or resource busy
2019/08/26 14:08:59 Unmount failure can cause images being incomplete!
```
`libostree` keeps some information, like _repo lock file descriptor_, in thread specific variables.
As _Go Garbage Collector_ can be run in a thread different from the one which created the `libostree` object, it may not been able to access the object thread specific variables, preventing to free them correctly.
To prevent this, explicitly dereference `libostree` objects.

ostree-deploy: fix umount error

---

TODO
actions/pack_action.go
archiver.go

Add options to `tar` to tell it to save and restore extended attributes:
* `--xattr`: enable extended attributes support
* `--xattrs-include=*.*`: tell `tar` to include every extended attribute
since by default `tar` only stores attributes in the `user.*` namespace
This fixes the `pack` and `unpack` actions when dealing with tools like
`ping` which on modern distributions have been switched to use file
capabilities to do privileged operations without being setuid, as they are
based on extended attributes.
This relies on `tar` being GNU Tar >= 1.27, released in 2013 and shipped since
Debian Jessie.
Tested with the recipe below:
```
architecture: amd64
actions:
- action: run
description: Create test file
chroot: false
command: touch "${ROOTDIR}/testfile"
- action: run
description: Set file …
```

pack,unpack: Save and restore xattrs and file capabilities in tarballs

---

cmd/debos/debos.go

When the detection of fakemachine detects kvm, it will always use it.
Even if kvm does not work properly.
Allow to disable it via commandline option.
Signed-off-by: Alexander Couzens <lynxis@fe80.eu>

Add option --disable-fakemachine

---

docker/Dockerfile

This makes the download action work when unpack is enabled and the downloaded file is of type zip.

docker: Add unzip

---

docker/Dockerfile

Add the u-boot-tools package to be able to use binaries such as
mkimage in debos' recipes.
Signed-off-by: Mylène Josserand <mylene.josserand@collabora.com>

docker: Add u-boot-tools package

---

commands.go

Added option `--timezone=off` for `systemd-nspawn` to leave the
file untouched during the chrooted calls.
Fixes: #180

commands: do not touch /etc/localtime in chrooted calls

---

actions/image_partition_action.go

Returning an error in this function causes the rest of the cleanup operation to
not be executed; so in this case downgrading an error to remove the mountpoint
from the read-only filesystem to a warning is wise.
Resolves: #206

actions/image_partition: do not return error if removing buildtime mountpoint with a read-only parent

---

actions/run_action.go

When a command is ran using `action: run` some environment variables are exposed to the script.
`$ROOTDIR` is set to `context.Rootdir=/scratch/root` which is a temporary
directory meant to hold the rootfs until `action: filesystem-deploy` is ran, which
copies from `context.Rootdir` to `context.ImageMntDir`. After the filesystem is
deployed, `context.Rootdir` is set to `context.ImageMntDir`.
The mount points defined under action: image-partition are mounted under
`context.ImageMntDir`, so if the filesystem is never deployed, there is no
(simple) way for the script to know where the images are mounted to.
So, expose `context.ImageMntDir` to the script as `$IMAGEMNTDIR` so the recipe
can know where the image is mounted.
Resolves: #204
Signed-off-by: Christopher Obbard …

action: run: expose context.ImageMntDir as $IMAGEMNTDIR

---

actions/filesystem_deploy_action.go

All the filesystem-deploy action does is copy the contents from scratch into the
mounted image, then all actions after that refer to the image rather than the
scratch space. Be clearer.
Resolves: #175

docs: action: filesystem-deploy: clarify what happens after deploy

---

actions/run_action.go

For the run action, debos does not complain even if both "script" and
"command" are empty which can occur due to a typo or accidentally
missing the tag.
As the documentation already mentions that one of "script" or
"command" is mandatory for the run action, let's detect the invalid
scenario and complain to the user instead of silently continuing.
Signed-off-by: Punit Agrawal <punit1.agrawal@toshiba.co.jp>

actions/run: Improve run action verification

---

actions/image_partition_action.go

F2FS requires a few tweaks to be usable within debos:
* its command-line option for setting the fs label is different from
other mkfs utils
* parted doesn't recognize "f2fs" as a valid filesystem, therefore it
shouldn't appear on the command line
With these simple changes, it becomes possible to use F2FS partitions
with debos.

actions: image_partition: add F2FS support

---

actions/debootstrap_action.go

Allow to use certificate and private key for client authentication.
Those action parameters falls thru `debootstrap` for `wget` allowing
to authenticate client on server side.

WIP: action/debootstrap: add certificate and private-key

---

cmd/debos/debos.go

The command-line argument parsing library already prints any parsing
errors; there's no need to print the error again ourselves.

cmd: Don't print command-line parsing error twice

---

actions/apt_action.go
actions/recipe.go

This property is a boolean value indicating if `apt update` will be run
before install package. Default value is 'true'.
Signed-off-by: Trung Do <trung1.dothanh@toshiba.co.jp>
Signed-off-by: Daniel Sangorrin <daniel.sangorrin@toshiba.co.jp>

actions/apt_action: Add property 'update'

---

actions/pack_action.go
actions/recipe.go

Match the same compression options as unpack and allow to have an uncompressed tar when removing the `compression` parameter.
Signed-off-by: Corentin Noël <corentin.noel@collabora.com>

actions/pack_action: Add several compression options

---

docker/Dockerfile

The equivs package is used to create dummy Debian packages which can
be useful in development to satisfy dependencies without installing the
real package. Note that this package is not the recommended way of
dealing with broken dependencies: a bug report should be filed instead.

docker: Add equivs package

---

docker/Dockerfile

Add the zip package to allow the cration of compressed zip archives.

docker: Add zip package

---

actions/run_action.go

Expose the environment variables $ARTIFACTDIR and $RECIPEDIR
to the postprocess commands to allow the postprocess commands
to be more flexible.

actions: run: Expose paths to postprocess commands

---

docker/Dockerfile

There are issues with qemu-user-static 5.2 crashing when attempting
to allocate guest memory when compiled as a proper statically-linked
binary.
From testing, qemu 6.0 fixes the bug but it's not yet clear which
patch fixes the bug. So until the correct patch is backported to
bullseye, let's install qemu from experimental to pickup the bugfix.
See: #245
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=988174

docker: Install qemu-user-static 6.0 to fix segfault

---

docker/Dockerfile

Debian's qemu-user-static package no longer registers binfmts on postinst
when running inside a virtualmachine; dockerhub builds are now built inside
a vm so the binfmts are not generated inside the docker container.
Fixes: 91af617bea07 ("docker: Install qemu-user-static 6.0 to fix segfault")

docker: Manually register binfmts

---

actions/raw_action.go

The documentation suggests that offset should be optional; in practice
offset isn't optional and the action will return an error out if unset:
Action `` failed at stage Run, error: Couldn't parse offset strconv.ParseInt: parsing "": invalid syntax
So set the offset by default to 0 then only attempt to parse the parameter
from the YAML if it is explicitly set.
Fixes: b792b4722acb ("Add a raw action")

actions: raw: Actually make offset optional

---

actions/image_partition_action.go
docker/Dockerfile

Currently support setting UUID for btrfs, xfs, ext2, ext3, ext4 file system
Signed-off-by: Nguyen Thi Huong <huong4.nguyenthi@toshiba.co.jp>
Signed-off-by: Daniel Sangorrin <daniel.sangorrin@toshiba.co.jp>

image-partition: Modify property 'fsuuid' to allow setting UUID

---

actions/image_partition_action.go

The "image-partition" action uses artifactdir in the
PostMachineCleanup() step but not during the PreMachine() and
PreNoMachine() steps. Also, other debos actions such as pack, unpack
are relative to the specified "artifactdir" when invoking debos.
Fix this inconsistency by bringing image-partition action to the
fold. Also update the documentation to clarify this.
Signed-off-by: Punit Agrawal <punit1.agrawal@toshiba.co.jp>

actions/image-partition: Consistently use artifactdir

---

actions/image_partition_action.go

The linked commit doesn't correctly initialise new
variables, so go fails to build:
../../../go/src/github.com/go-debos/debos/actions/image_partition_action.go:371:2: undefined: ImagePath
../../../go/src/github.com/go-debos/debos/actions/image_partition_action.go:372:26: undefined: ImagePath
../../../go/src/github.com/go-debos/debos/actions/image_partition_action.go:384:34: undefined: ImagePath
So fix the initialisation of these variables, while
there improve the case of the variable names to be
more consistant with the rest of the project.
Fixes: a7afc01562bf ("actions/image-partition: Consistently use artifactdir")
cc @punitagrawal

actions: image-partition: Fix build failure

---

docker/Dockerfile

qemu is no longer in experimental so the container build
will now fail. The required patches for qemu have been
backported into bullseye so let's revert using qemu from
experimental.
Link: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=988174

docker: Don't use qemu from experimental 

---

.github/dependabot.yml

Dependabot should automatically create pull requests when go
modules are updated. This should then run the CI scripts to
make sure fakemachine is built and tested on each supported
version of Go.

ci: Keep dependencies up-to-date using dependabot

---

actions/run_action.go

When a multiline command is used with "run" action, it’s sometimes
difficult to figure out what’s going on, as it’s printed in its entirety
for the each line of its own output. For example:
```yaml
- action: run
chroot: false
command: |
echo test1
echo test2
echo test3
```
Prints this:
2022/04/15 10:52:46 echo test1
echo test2
echo test3
| test1
2022/04/15 10:52:46 echo test1
echo test2
echo test3
| test2
2022/04/15 10:52:46 echo test1
echo test2
echo test3
| test3
For clarity, it’s better to only use the first line:
2022/04/15 11:03:10 echo test1... | test1
2022/04/15 11:03:10 echo test1... | test2
2022/04/15 11:03:10 echo test1... | test3

For multiline commands, only use the first line and "..." as the label

---

actions/image_partition_action.go

Some underlying device driver, e.g. the UML UBD driver, may manage holes incorrectly which will prevent to retrieve all usefull zero ranges in filesystem, e.g. when using 'bmaptool create'
Assigning `UNIX_IO_NOZEROOUT` environment variable prevent mkfs.ext[234] utilities to create zero range spaces using fallocate with `FALLOC_FL_ZERO_RANGE` or `FALLOC_FL_PUNCH_HOLE`

Prevent ext[234] filesystems corruption

---

actions/image_partition_action.go

When removing loop devices, we retry after a delay with
a timeout. Each time the loop device removal fails, a
warning message is printed to the log:
"Loop dev couldn't remove could not remove, device in use, waiting"
This is pointless and could confuse the user. An error
while performing the loop device removal & retry is
logged seperately so let's remove the duplicate (and
confusing) log message.

actions: image-partition: Remove extra warning about removing loop device

---

actions/image_partition_action.go

Image partitions should be allowed to create with two different
unit measurements binary and decimal.
binary units(KiB, MiB, GiB, TiB, PiB) are calculated in multiples of 1024,
and decimal units(KB, MB, GB, TB, PB) are caculated in multiples of 1000.
e.g:
imagesize: 1GiB = 1073741824
imagesize: 1GB  = 1000000000
Signed-off-by: venkata pyla <venkata.pyla@toshiba-tsip.com>

actions/image-partition: Allow binary unit measurements in the imagesize

---

actions/debootstrap_action.go

Currently running the debootstrap action inside a fakemachine results
in the following warning:
Debootstrap | W: Unable to read /etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory
Make sure the directory exists in the fakemachine host before running
the debootstrap command.
Fixes: #219

debootstrap: Make sure /etc/apt/apt.conf.d exists

---

.github/workflows/ci.yaml

For faster developer feedback, kick off a test build and the unit test suite inside pre-made containers. This allows the job to fail-fast since a developer doesn't need to wait for a Docker container to be built.
This also has the benefit of testing Debos on various platforms other than the final Docker container.

ci: Run tests inside test container

---

README.md

For me as a user it was unclear to me what kind of penalty there is for not allowing access to /dev/kvm, so I timed how long building pine-a64-plus/debian.yaml takes for the different backends.
I did not use the rpi recipes as they spend a lot of time downloading firmware blobs.
The tested debos version is 82c36d07b37c1818812ed63ec868c052f1b936a0 (current main at the time of writing) and the benchmarks have been run on an otherwise-idle box with the following specs:
* Debian Bullseye AMD64 (kernel 5.10.92)
* go version go1.15.15 linux/amd64
* 4 x Intel(R) Pentium(R) CPU G4560T @ 2.90GHz
* Fast M.2 SSD
* 24 GiB of RAM
For posterity, the very simple benchmark script is attached below:
#!/bin/bash
set -eux
time sudo debos --disable-fakemachine debian.yaml
time debos -b kvm debian.yaml
time …

README.md: add benchmarks for the different backends

---

actions/image_partition_action.go

Extended options can be used for specific file system tuning.

image_partition_action: Add support for FS extended options

---

actions/apt_action.go
actions/debootstrap_action.go
actions/download_action.go
actions/filesystem_deploy_action.go
actions/image_partition_action.go
actions/ostree_commit_action.go
actions/ostree_deploy_action.go
actions/overlay_action.go
actions/pack_action.go
actions/raw_action.go
actions/recipe_action.go
actions/run_action.go
actions/unpack_action.go

The yaml examples get somewhat mangled on godoc.org currently.
Example from https://pkg.go.dev/github.com/go-debos/debos/actions@main#hdr-Recipe_syntax :
action: apt recommends: bool unauthenticated: bool update: bool packages:
package1
package2
Adding a blank line in front of the blocks makes the examples render as preformatted text.

godoc: add blank line in front of yaml examples

---

actions/apt_action.go
actions/debootstrap_action.go
actions/download_action.go
actions/filesystem_deploy_action.go
actions/image_partition_action.go
actions/ostree_commit_action.go
actions/ostree_deploy_action.go
actions/overlay_action.go
actions/pack_action.go
actions/raw_action.go
actions/recipe_action.go
actions/run_action.go
actions/unpack_action.go

Unfortunatley, 191c474477af4cc679779dd4eb70f28c1d9dbd62 was not enough to fix the yaml code block rendering on godoc.org.
The problem is that a block that starts with "-", even if indented, is interpreted as a list.
The only solution I found was to pull the "Yaml syntax:" line into the code block as a comment.
This fixes the rendering of the code block as verified by running "go doc actions" on the command line (see below):
Rendering of the YAML block using "go doc actions | head -20", before this change:
package actions // import "github.com/go-debos/debos/actions"
Package 'actions' implements 'debos' modules used for OS creation.
Install packages and their dependencies to the target rootfs with 'apt'.
Yaml syntax:
- action: apt recommends: bool unauthenticated: bool update: bool …

godoc: fix magled yaml code blocks, take two

---

actions/actions_doc.go

Getting the raw action to work with an actual file was somewhat confusing for me.
Looking at the code, the origin is searched for in context.Origins, which is only set in three places:
$ git grep Origins
download_action.go:     context.Origins[d.Name] = originPath
filesystem_deploy_action.go:    context.Origins["filesystem"] = context.ImageMntDir
ostree_deploy_action.go:                context.Origins["filesystem"] = context.ImageMntDir
In addition, "recipe" is special-cased in DebosContext.Origin.
List all four options to hopefully make it less confusing for the next person.

docs: RawAction: list possible values for origin

---

actions/image_partition_action.go

Earlier commit added image locking around the partition handling. Yet we forgot to unlock in the error path - fix that.
Fixes: 1002e0a ("image-partition: Minimize the image lock scope")

image-partition: add unlock() in the error paths

---

tests/partitioning/test.yaml

There are various whitespace changes that can occur in json files. Use the same pretty-format in both files to ensure the output is stable and consistent.
Note: we need to explicitly call "bash -c" here otherwise, we'll end up with pure POSIX shell (sh), where anonymous pipes are not a thing.
Signed-off-by: Emil Velikov <emil.velikov@collabora.com>

tests: process json files throgh jq prior to comparing

---

actions/overlay_action.go
filesystem.go

Currently the overlay action prints directly to stdout, which
ends up not following the standard output format the other
actions follow. Let's clean this up by using the action's
existing logging functions rather than printing directly
to stdout.

actions: overlay: Log using action log functions

---

.github/workflows/ci.yaml
README.md
actions/pacman_action.go
actions/pacstrap_action.go
actions/recipe.go
doc/man/debos.1
docker/Dockerfile
tests/arch/mirrorlist
tests/arch/pacman.conf
tests/arch/test.yaml

This PR adds support for creating pacman based images (be that Arch or alike). Similar to the Debian variant we have two important actions - pacstrap and pacman.
- pacstrap, requires pacman.conf and mirrorlist files
- pacman is a simple list of packages, just like apt
This PR supersedes https://github.com/go-debos/debos/pull/276 and https://github.com/go-debos/debos/pull/277, where the most significant changes are within the pacstrap action. In particular, we no longer write the config/mirrorlist files.
Considering that pacman is changing faster than debos, it makes sense to have the files as drop-ins instead of trying to hard-code them within debos itself.
Note: the final commit adds a simple CI file, which is not wired. Tips on how to achieve that would be appreciated.

Arch support - aka pacstrap, pacman and tests

---

actions/debootstrap_action.go

The workaround for https://github.com/go-debos/debos/issues/361 that was applied in https://github.com/go-debos/debos/commit/b3c1f76bcc1dbd55fef584b8ddbda33f12733116 breaks recipes for bookworm and newer.
This change makes the workaround less damaging (should atleast work with official debian releases for the forseeable future), while still far from perfect (any derivate distribution that is bookworm-based will fail).

Limit old suite workaround

---

.github/workflows/ci.yaml

The option is deprecated and we should be using $GITHUB_OUTPUT instead. See the official announcement for details:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: remove deprecated set-output

---

filesystem.go
tests/overlay-non-existent-destination/overlay-non-existent-destination.yaml

If the overlay action fails to copy a file into the target filesystem
(e.g. destination path inside the filesystem doesn't exist), the current
behaviour is to panic, which causes a debos call inside the fakemachine
to panic, which isn't detected by the outer debos call.
This causes the exection of the inner debos call to stop (i.e. the
remaining recipe actions are no longer ran which is expected), but the
postexec commands still run and the overall exection is marked as
successful!
Rework the panics to instead bubble up errors so that any errors when
overlaying files causes the recipe to error out correctly rather than
this unexpected behaviour.

filesystem: Bubble up errors rather than panicing

---

actions/apt_action.go

Showing the update progress can cause non-interactive shells which do not support moving the cursor to become confused and not show the correct output. For instance, GitLab CI ignores any line which attempts to move the cursor, meaning some output for the apt action is just discarded.
Disable the apt progress from being shown and instead only showing the apt output log.

actions: apt: Don't show progress update percentages

---

.github/workflows/ci.yaml

Requires https://github.com/go-debos/test-containers/pull/18

ci: Add debian trixie to the test matrix

---

actions/debootstrap_action.go

Check if suite property is present for debootstarp action and contains
a string. If suite is not present, exit with an error.
Fixes: #238
Signed-off-by: Vignesh Raman <vignesh.raman@collabora.com>

action/debootstrap: make suite property mandatory for debootstrap action

---

docker/Dockerfile

Bookworm is stable since June. So let's update the Dockerfile to use it so we can get rid of all the backports.
This required to add the systemd-resolved package as it was split into a separate package from systemd-networkd.
Motivation for the upgrade was have dpkg with zstd support so we can debootstrap Ubuntu again.

docker: update to Debian 12 (Bookworm)

---

docker/Dockerfile

The arch linux tests require a newer version of archlinux-keyring than what is in Debian stable; so revert back to pulling the latest version.
This partially reverts 36cf33366bbe0dd602185a87a241ff070517f868.

docker: Install archlinux-keyring from source

---

action.go
actions/apt_action.go
actions/debootstrap_action.go
actions/download_action.go
actions/filesystem_deploy_action.go
actions/image_partition_action.go
actions/ostree_commit_action.go
actions/ostree_deploy_action.go
actions/overlay_action.go
actions/pack_action.go
actions/pacman_action.go
actions/pacstrap_action.go
actions/raw_action.go
actions/recipe_action.go
actions/run_action.go
actions/unpack_action.go
cmd/debos/debos.go

Currently each action starts with LogStart(), adding some annoying duplication. In addition we have a LogStart(), whereas there's no end/stop equivalent.
Instead add the on-line log.Print() wihtin the debos action loop, just prior to calling Run(). The same file deals with all the other pretty logging.
NOTE: this conflicts trivially with https://github.com/go-debos/debos/pull/377

action: move and inline LogStart() further up

---

docker/Dockerfile

This adds the Debian ports keyring, which allows debootstrapping Debian port architectures (see https://www.ports.debian.org/).
Fixes #463.

Docker: Add Debian ports keyring

---

.github/workflows/ci.yaml

kvm is the recommended backend for fakemachine; Unfortunately github hosted runners don't always support virtualization[0]. Luckily the debos organisation now has a kvm supported self-hosted runner sponsored by Collabora, so use that for kvm tests.
This also simplifies the matrix properties for jobs, moving their quirks into expressions instead. Simple tests for building non-debian distributions (arch, apertis) are now ran on kvm as well
0: The github-hosted runners are sometimes the documented intel xeon
based-instance type without virt support.. and sometimes amd epyc
with virt support.

Also run tests on self-hosted kvm runner

---

.github/workflows/ci.yaml

In go-debos/test-containers#30 we simplified the test containers by only creating one container for both fakemachine/debos instead of creating separate containers for each project. Use the new container.
Draft because:
- Depends on https://github.com/go-debos/test-containers/pull/30
- Container tag needs to change to main

ci: use generic test container

---

actions/debootstrap_action.go
commands.go

With fakemachine now being compatible with arm64 hosts, it is possible to build and run debos on this architecture. However, it will still assume it runs on amd64, hence executing actions in the chroot through qemu and calling debootstrap with the `--foreign` flag set, even when building for the same architecture.
This PR makes use of runtime architecture detection to avoid those unnecessary tricks.

Be nicer to non-amd64 hosts

---

actions/image_partition_action.go

If the filesystem type is 'none', it results in the below error.
==== image-partition ====
Action `image-partition` failed at stage Run, error: root mount failed: no such device
Warning: Failed to get unmount /boot/efi: no such file or directory
Unmount failure can cause images being incomplete!
Powering off.
Report an error message if filesystem type is 'none' and exit.
Fixes: #234
Signed-off-by: Vignesh Raman <vignesh.raman@collabora.com>

actions/image-partition: check if the filesystem is mountable

---

.github/workflows/ci.yaml
actions/image_partition_action.go
tests/msdos/expected.json
tests/msdos/test.yaml

This commit allows us to create extended or logical
partitions on MBR partition table (msdos) in order to
address the following issues:
* Because part-type for parted is hardcoded with primary,
we cannot create more than 4 partitions using extended and
logical.
* Even if we manage to create extended and logical partitions,
the verificaton step fails because the Verify function assumes
that the partition number is always sequetially incremental.
This commit makes it possible that if the number of partitions
is more than 4, 3 of them are automatically created as primary,
1 of them is extended, and the remaining partitions are logical.
Signed-off-by: Daniel Sangorrin <daniel.sangorrin@toshiba.co.jp>
Signed-off-by: Daichi Fukui <daichi1.fukui@toshiba.co.jp>

actions/image-partition: allow extended and logical

---

cmd/debos/debos.go

Hi! Thanks for the work on this useful project.
We have successfully been using debos for some time, but it always prints the whole debos invocation, which causes secrets passed into debos as variables (e.g. account passwords, private keys) to be written to our CI logs. I looked into this and found that it was because fakemachine logs the command it runs by default, though it has an option to suppress this. I saw no way of setting this option through debos, though, hence this pull request.
This pull request adds the flag "--quiet-fakemachine" because it was the least intrusive change, but on a second thought, it looks a bit odd. I think it might make more sense to use the quiet option in fakemachine by default, and let the existing debos flag "--verbose" disable it instead. What do you …

Add option to quiet fakemachine

---

commands.go

Currently the default nspawn console mode for nspawn is interactive which means that /dev/console is created inside the nspawn container and the command can assume it is running in an interactive session.
With console mode set to pipe, nspawn doesn't create /dev/console inside the container and scripts assume they are running in an interactive environment
This has the benefit of forcing some commands (e.g. apt) to not show things like progress bars which only work in interactive terminals.
Fixes: #411
Fixes: #416

commands: Set nspawn console mode to pipe

---

docker/Dockerfile
docker/get-archlinux-keyring.sh

Currently rebuilding the arch keyring on Debian bookworm is broken as the build depends  on newer sq options. There is no reason to re-build the keyring though, debian also uses a pre-build version to package it for example.
Switch to use a script to download the latest release from arch gitlab

docker: Use prebuild archlinux keyring

---

actions/actions_doc.go

The 'artifacts' value for the origin property was missing from the documentation. Add it.

actions: Document 'artifacts' value for the origin property

---

actions/image_partition_action.go

actions: image-partition: enable creation of FAT{12|16|32} partitions

---

actions/download_action.go

From the path module doc:
If the path is empty, Base returns ".". If the path consists
entirely of slashes, Base returns "/".
Actually validate that we provide a filename when one is required, rather than failing with an error that /scratch exists but is not a file.

download: Actually validate empty pathnames

---

actions/recipe.go
actions/recipe_test.go

When we're unpacking individual actions, pass YAML parsing errors up to the caller instead of silently ignoring them.
Also add a test that checks that debos more obviously errors out when you do what I tried to do.

Don't ignore YAML parsing errors

---

actions/image_partition_action.go

The regression was introduced with the following commit :
commit 94fedb2c0c8a97ceb7c9b153aefa81c8d94ce57b
Author: Christopher Obbard <chris.obbard@collabora.com>
Date:   Tue Mar 19 17:43:42 2024 +0000
actions: image-partition: enable creation of FAT{12|16|32} partitions
This one added more options when it comes to creating FAT partitions. So when partition fs is defined as "fat", "fat12", "fat16", "fat32", "msdos" or "vfat", then mkfs.vfat is used to create the partition, and different options were used depending on the FAT type.
The main issue is that  mounting a FAT partition should  use "vfat"
as fs type when using syscall.Mount().
So, in order to fix this issue, "vfat" is simply used to mount "fat", "fat12", "fat16", "fat32" or "msdos" partitions.

actions: Fix regression introduced with FAT{12|16|32} support.

---

actions/image_partition_action.go

Recent changes introduced a tuned formatting of the partitions created with FAT{12|16|32}. The issue is that fstab is generated using the fs property which won't match the system expectations.
If the fs property is "fat", "fat12", "fat16", "fat32" or "msdos", then fstab must use "vfat".

actions: fix fstab generated in case of FAT{12|16|32}.

---

.github/workflows/ci.yaml
docker/Dockerfile

Follow-up of @tboehler1 's #505 as suggested by @obbardc 
Convert Dockerfile so multiple target architecturebuilds are possible. Also modify the CI pipeline, in order to built a single multi-platform container.
Note that at the current time-being docker cannot export multi-platform containers without an intermediate registry. Thus only the amd64 image is exported for the test stage. Nevertheless the arm64 image is built in the pipeline and also published later to the registry.
If the go-debos project has access to GitHub large runners, the pipeline could be reworked in order to build the container on a native arm runner. This would bring a significant speed improvement and also would allow for testing the arm container. But for know this solution should be sufficient as it tests the build …

docker: Add arm64 builds to Dockerfile and CI

---

cmd/debos/debos.go

This 'version' option prints the debos version. Fix: #430

cmd: Add 'version' option

---

actions/image_partition_action.go
go.mod
go.sum

We were stuck in 2017 (v1.0.0-20170407175016-fc9adea44124).
Related: https://github.com/go-debos/debos/issues/522

deps: bump go-losetup to latest v2 release

---

actions/image_partition_action.go

losetup.Attach() can fail due to concurrent attaches in other processes as seen in https://github.com/go-debos/debos/issues/522 .
The problem is a race condition between finding a free loop device and attaching the image.
Now that we have go-losetup v2, which does report the error, we can do what util-linux does
( https://github.com/util-linux/util-linux/blob/4c4b248c68149089c8be2f830214bb2be693307e/sys-utils/losetup.c#L662 ) and retry on failure.
I only sleep for 200 ms as opposed to 1 second as in https://github.com/go-debos/debos/blob/78aad24dc068ec2aac0355c165f760b953379b8f/actions/image_partition_action.go#L668 because the race condition should immediately resolve without waiting at all.
I still sleep for 200 ms as this is what util-linux does to prevent spinning ( …

ImagePartitionAction: retry losetup.Attach()

---

actions/filesystem_deploy_action.go

Small improvements to filesystem-deploy action

---

README.md

This fix the link since the default branch name has changed. Fix #520

README: use relative link to docker/README.md

---

actions/image_partition_action.go

Added optional fslabel property to partition to allow truncation of filesystem
label and allow user to modify filesystem label without modifying the name.
Filesystem label defaults to the name property of the partition.
The filesystem label can be up to 11 characters long for vfat, 16 characters
long for ext2/3/4, 255 characters long for btrfs, 512 characters long for
hfs/hfsplus and 12 characters long for xfs.
Fixes: #251
Suggested-by: Christopher Obbard <chris.obbard@collabora.com>
Signed-off-by: Vignesh Raman <vignesh.raman@collabora.com>
Signed-off-by: Dylan Aïssi <dylan.aissi@collabora.com>
This MR is based on @vigneshraman 's work from https://github.com/go-debos/debos/pull/271.

actions/image-partition: truncate filesystem label to maximum supported length

---

cmd/debos/debos.go

Since the --memory and --scratchsize arguments are parsed with human-readable suffixes into bytes (e.g 2048MB or 2GB), if a user does not put a suffix the arguments are parsed as bytes which can cause issues later when a user sets the memory to be 2048 assuming it will be parsed as MB.
Change the documentation to match reality and also add a warning if the user has set either parameter less than the recommended default.
Closes: #509

Warn if parsed memory/scratchsize may be too small

---

.github/workflows/ci.yaml
actions/mmdebstrap_action.go
actions/recipe.go
docker/Dockerfile
tests/debian/test.yaml

Add mmdebstrap [1] as a faster and more flexible alternative to debootstrap.
[1] https://gitlab.mister-muffin.de/josch/mmdebstrap
I am not really familar with go (day to day language is Python or C). Therefore I ask for your patience :-)
Example recipe on a Raspberry Pi 5 in docker container with KVM enabled:
```
---
{{- $architecture := or .architecture "arm64"}}
{{- $tool := or .tool "mmdebstrap" }}
architecture: {{$architecture}}
actions:
- action: {{ $tool }}
suite: bookworm
variant: minbase
- action: apt
description: Install some base packages
packages:
- procps
```
With `deboostrap`:
```
real    0m53.590s
user    0m38.792s
sys     0m25.345s
```
With `mmdebstrap`:
```
real    0m33.400s
user    0m24.239s
sys     0m8.838s
```
=> 20 seconds faster. I plan to build a kinda …

actions: Add mmdebstrap action

---

tests/arch/pacman.conf

The community repositories were merged into extra around to years ago. Recently the database files got cleaned up on the mirrors, causing errors in CI. Adjust pacman.conf to remove these deprecated repositories
See https://archlinux.org/news/cleaning-up-old-repositories/ for more details

tests: arch: remove deprecated repositories

---

actions/mmdebstrap_action.go
tests/debian/test.yaml

The mmdebstrap process fails because the format contains single quotation.
To fix this, remove single quotation (') from the append strings of dpkgopt and aptopt.
Debos yaml file:
```
architecture: amd64
actions:
- action: mmdebstrap
suite: sid
variant: minbase
merged-usr: true
dpkg-opts:
- path-exclude=/usr/share/man/*
```
Error message:
```
[...]
2025/03/03 06:59:12 Mmdebstrap | dpkg: error: configuration error: /etc/dpkg/dpkg.cfg.d/99mmdebstrap:1: unknown option ''
[...]
```
From debug message of mmdebstrap:
```
[...]
D: 1 3180 content of /etc/dpkg/dpkg.cfg.d/99mmdebstrap:
'path-exclude=/usr/share/man/*' <--here
apt 2.9.30 (amd64)
Supported modules:
*Ver: Standard .deb
[...]
```

Fix mmdebstrap action

---

cmd/debos/debos.go

The original commit adds a --version argument to debos but the version is hardcoded which is a bit awkward. Since we haven't shipped this commit in a release yet, revert it to allow the proper implementation to be completed in the next version of debos.
This reverts commit f13268b17345065d3f17397b66046d913a540a10.

Revert "cmd: Add 'version' option"

---

cmd/debos/debos.go

Currently debos fails if an action attempts to use artifactdir and it doesn't exist on the host:
$ debos --artifactdir=out rpi64/debimage-rpi64.yaml
Action `image-partition` failed at stage PreMachine, error: open /home/obbardc/projects/debos/debos-recipes/out/debian-rpi64.img: no such file or directory
Check that artifactdir exists early and return an error in case that it does not exist.
Closes: #426
This PR is based on https://github.com/go-debos/debos/pull/429 but using `context.State` to track errors since https://github.com/go-debos/debos/pull/555 is now merged.

Check if artifactdir exists early

---

.github/workflows/ci.yaml

Since forky is the codename for the new version of debian testing, run the CI tests under forky.

Run CI tests under debian-forky

---

.github/workflows/ci.yaml
.golangci.yml
action.go
actions/actions_doc.go
actions/apt_action.go
actions/debootstrap_action.go
actions/download_action.go
actions/filesystem_deploy_action.go
actions/image_partition_action.go
actions/mmdebstrap_action.go
actions/ostree_commit_action.go
actions/ostree_deploy_action.go
actions/overlay_action.go
actions/pack_action.go
actions/raw_action.go
actions/recipe.go
actions/recipe_action.go
actions/recipe_test.go
actions/run_action.go
actions/unpack_action.go
archiver.go
archiver_test.go
cmd/debos/debos.go

Ensure that submitted merge requests are run through a linter check to keep high code quality.
Initially run just a formatting check due to code quality issues. Once merged we can enable useful linters one-by-one after fixing each issue.
Closes: #378

ci: Add linter stage to workflow

---

.gitignore
.golangci.yml
actions/debootstrap_action.go
actions/download_action.go
actions/filesystem_deploy_action.go
actions/image_partition_action.go
actions/ostree_deploy_action.go
actions/overlay_action.go
actions/pack_action.go
actions/pacstrap_action.go
actions/raw_action.go
actions/recipe.go
actions/recipe_action.go
actions/recipe_test.go
actions/run_action.go
actions/unpack_action.go
archiver.go
archiver_test.go
cmd/debos/debos.go
commands.go
filesystem.go
net.go
os.go

Add support for staticcheck: fix all issues reported by staticcheck and run it
as part of CI.
Note the ioutil changes break backward compatibility with very old golang by
addressing deprecations from 1.19, but the oldest supported Debian release
seems to be bookworm, and it has a newer golang than that.
Did a couple of gitignore tweaks along the way.
Commits:
- **fix: Incorrectly formatted error string (ST1005)**
- **fix: Unnecessary use of fmt.Sprintf (S1039)**
- **fix: Omit comparison with boolean constant (S1002)**
- **fix: Using a deprecated function, variable, constant or field (SA1019)**
- **fix: Deferring Close before checking for a possible error (SA5001)**
- **fix: Use a single append to concatenate two slices (S1011)**
- **fix: Break statement with no effect (SA4011)**
- **fix: …

Misc static analysis fixes

---

commands.go

When you have multiple debos chroot builds running at the same time, you will get something like this:
2025/09/16 11:17:38 apt | Mount point '/run/systemd/nspawn/unix-export/root' exists already, refusing.
2025/09/16 11:17:38 Action `recipe` failed at stage Run, error: exit status 1
This because systemd-nspawn will name the container acc. to the root directory per default, which is always "root" for debos, and wants to create a subdir inside "/run/systemd/nspawn/unix-export" even with "--register=no".
To reproduce this problem, you need two copies of a root file system where the last component of the path has the same name.
The example below was run on Debian Trixie arm64 and uses ~/trixie1/trixie and ~/trixie2/trixie as the root directories:
1st terminal:
root@jaguar1:~/trixie1/trixie# …

commands: systemd-nspawn: randomize machine name
